### ISSUE TITLE
Feature request: Parse different root directory from motioneye config file

### ISSUE THREAD

**Issue by Barmunksu** [DavHau/motioneye-loop-record#1]
Hello. If you add the ability to view the config file, you will no longer need to specify -d /data/output/

like this:
`-c , --config CONFIG path to motioneye config file (default: /etc/motioneye/motioneye.conf)`

and in 99% of cases it will work:
`/data/etc/loop_delete.py -s 500`

**Comment by DavHau** [comment]
Great idea. Could you send a PR? :)
